### ISSUE TITLE
Other (strata lines, sea lions, etc.)

### ISSUE THREAD

**Issue by bethanyriggle** [afsc-gap-products/GOA-Survey-Planning#4]
Both Globe and ArcMap files will need to be updated.

**Comment by bethanyriggle** [comment]
Rebecca Reuter provided a site link which she believes has the most recent SSL critical habitat shapefiles. Ned and I are still investigating to see if there are any other current ones, but we should use this site in the meantime. 

https://www.fisheries.noaa.gov/resource/map/steller-sea-lion-western-dps-critical-habitat-map-and-gis-data

**Comment by MarkZimmermann-NOAA** [comment]
Ok, thanks for that.
Are you able to plot this ok?

Any more thoughts about plotting the crab pot storage in ArcMap?
-Mark
