### ISSUE TITLE
Vet and test tablet apps

### ISSUE THREAD

**Issue by bethanyriggle** [afsc-gap-products/GOA-Survey-Planning#68]
(Megsie edits, include for next year's task list):

# Functionality to test on apps:
## Catch app
- Change settings for vessel/recorder/year/etc.
- Enter a mixture
- Enter catch without a count and make sure it gives you an error
- Change voice and battery settings
- Testing out the new way we're supposed to wake them up (different for catch and length tablets this year?)
- Create raw Metis files and transfer to Metis computer via Bluetooth

## Crab app
- No idea....

## Length app
- Pair via Bluetooth with wand and speaker
- Change voice settings
- Wake up in the new way we're supposed to wake them up (without Shake)

## Need to add more...

**Comment by SarahFriedman-NOAA** [comment]
Other things to check:
- make sure new otolith standards are updated in specimen app 
- Change specimen number
- Test visual maturity stuff


Notes:
- have folks load .apk files during tablet training to spread around work load
-

**Comment by MargaretSiple-NOAA** [comment]
I think we'll need a little more time on these. Only need to:
- make sure new otolith standards are updated in specimen app
- Test visual maturity stuff -- make sure maturity schedule for special project is identifiable in the app and there are adequate instructions for recording it.

**Comment by MargaretSiple-NOAA** [comment]
@SarahFriedman-NOAA I forgot to save a tablet for you to check the oto standards and maturity schedule on, but would you mind checking those on one of the tablets later this week or next? It'll be the same on all of them so we only need to check one. I haven't looked at the special projects to see which maturity schedule they use and whether it's in the app. We'll want to check that too.

**Comment by SarahFriedman-NOAA** [comment]
I checked and it looks like we're good on the oto standards. Re: the maturity scales -- there are a lot of options available on the tablets for maturity scale settings, but they aren't specified in the special project proposal as far as I can tell. Many of the options are species-specific (e.g. 14 - anatomical maturity scale for northern rock sole, 1 - general maturity codes) so I assume we would stick to those, but perhaps @smcdermo can weigh in since it is her project?

**Comment by Ned-Laman-NOAA** [comment]
Thanks, Sarah.
100% agree that @smcdermo needs to provide or point to the correct maturity table for her project. These scales are not only species-specific but are often project-specific as well. If Susanne's chosen scale isn't already in the system, she'll need to load it onto the tablets now or at sea so should prepare for that possibility.

**Comment by MargaretSiple-NOAA** [comment]
Sus- I think if you're the person collecting the data this makes sense; just make sure the maturity schedule you want to use is in the app (there are many options!) and that the people you train on your boat know which one to use for cod and which one to use for rockfish. Anyway, as long as the tools you need are in the tablets in their current state, I think we're good.

**Comment by smcdermo** [comment]
Hi Margaret. The maturity codes used are in the tables. I talked with Sandi and the one for Pcod can be used. I don’t think they will get loaded into the app. They just have to be matched to the oracle tables later but maybe I am wrong. Can we talk on Monday?  I am out of town until then. SusSent from my iPhoneOn Apr 6, 2023, at 11:24 AM, Margaret Siple ***@***.***> wrote:﻿
Sus- I think if you're the person collecting the data this makes sense; just make sure the maturity schedule you want to use is in the app (there are many options!) and that the people you train on your boat know which one to use for cod and which one to use for rockfish. Anyway, as long as the tools you need are in the tablets in their current state, I think we're good.

**Comment by MargaretSiple-NOAA** [comment]
Hi Sus- As long as you have what you need on the tablets for your tagging project w/r/t maturity codes, it's all good. We just wanted to make sure what you need is on there before the tablets get shipped up.
