### ISSUE TITLE
Testing and set up of METIS/GIDES at sea

### ISSUE THREAD

**Issue by bethanyriggle** [afsc-gap-products/GOA-Survey-Planning#69]

**Comment by MargaretSiple-NOAA** [comment]
I forget how this is different from #7 . Do we need to test any additional functionality? Maybe we are going to test the full process, starting with raw data transfer from tablets to Metis computer?

**Comment by Ned-Laman-NOAA** [comment]
This may be a hold over from last year when we were particularly concerned that we test Metis/GIDES @sea on our test tows to make sure all was well and we didn't need to revert to dataent. I still think that this activity is a prudent idea before we get too far from Dutch on the first leg, but could be convinced that it doesn't require a line in the Task List. @bethanyriggle - what do you think?

**Comment by bethanyriggle** [comment]
I think it is important to test METIS out at sea, but I don't think it should be a Task List item in the future. Should be added to Leg 1 deck lead responsibilities, if there is a still a document out there that lists all of that!

**Comment by SarahFriedman-NOAA** [comment]
Yes, @zoyafuso-NOAA has been managing that part of the RACE Survey App

**Comment by MargaretSiple-NOAA** [comment]
I have changed the due date to May 15 so we do it at sea.
