### ISSUE TITLE
ArcMap

### ISSUE THREAD

**Issue by bethanyriggle** [afsc-gap-products/GOA-Survey-Planning#71]
ArcMap is one of the only things not covered during BDAWG training, so a separate training will need to be conducted for FPC's on the GOA survey.

**Comment by bethanyriggle** [comment]
Include explanation for how to add crab pot storage location layers to computers at sea if we have updated layers after the vans get shipped up.

**Comment by bethanyriggle** [comment]
April 12 there is a GOA group meeting, and since Ned will be gone, he suggested that we still hold the meeting, but gear it towards training everyone up on ArcMap.

**Comment by MarkZimmermann-NOAA** [comment]
I think I can do this, as long as I don't have a conflict with my new
LANTERN gig.
Still figuring out the commitments needed.
There will be a lot of meetings that I need to attend.
-Mark

**Comment by bethanyriggle** [comment]
ArcMap training completed on 04/12. Powerpoint will be included in Files for Boats for reference.
